package admin.bot.adminmoviebot.bot.constants;

public enum BotState {
  ST_START,
  ST_MOVIE_CODE,
  ST_ENTER_MOVIE_NAME,
  ST_CHOOSE_LANGUAGE,
  ST_MOVIE_QUALITY,
  ST_MOVIE_SIZE,
  ST_MOVIE_LENGTH,
  ST_MOVIE_RUNTIME,
  ST_MOVIE_YEAR,
  ST_MOVIE_CONFIRM,
  ST_REVIEW_ADDED_MOVIE,
  ST_EDIT_MOVIE,
  ST_MENU
}
